### ISSUE TITLE
Your Authorization Bearer Token must have read-write-delete access to your firewall rules.

### ISSUE THREAD

**Issue by gingerlime** [wpkc/fail2ban-action-cloudflare-restv4-bearer-token#1]
Hi @wpkc and thanks for sharing this!

I'm curious about the CF permissions for the token... you say that

> Your Authorization Bearer Token must have read-write-delete access to your firewall rules.

but can you be a bit more specific? I'm trying to set it like this:

![image](https://user-images.githubusercontent.com/524274/149093847-6b6fb920-9b00-4fc5-837d-6717b633181a.png)

The token seems valid, but I'm getting an authentication error ... 

```
# curl -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" -H "Authorization: Bearer ****" -H "Content-Type:application/json"
{"result":{"id":"5d420f798651186121fbb65b1e3f9339","status":"active"},"success":true,"errors":[],"messages":[{"code":10000,"message":"This API Token is valid and active","type":null}]}


# curl -X GET "https://api.cloudflare.com/client/v4/accounts/****/firewall/access_rules/rules" -H "Authorization: Bearer ****" -H "Content-Type:application/json"
{"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}
```

**Comment by gingerlime** [comment]
I think I figured it out :)

![image](https://user-images.githubusercontent.com/524274/149094829-c450fb50-d0b2-4db8-9729-10646744de90.png)

Cloudflare becomes the new AWS with lots of overlapping products and names :-/

**Comment by wpkc** [comment]
Glad you figured it out.  Thanks for sharing your solution.
