### ISSUE TITLE
Proposed changes for actionunban

### ISSUE THREAD

**Issue by c0f** [wpkc/fail2ban-action-cloudflare-restv4-bearer-token#3]
Hi, first of all thank you very much for providing this code. It helped me enormously because I was blissfully unaware that my Fail2Ban bans were not really being implemented!

I'd like to suggest a few changes to the actionunban line in cloudflare-restv4-bearer-token.conf:

1) Changing 'python' to 'python3'.
2) Updating the print statement for compatibility with python3.
3) Removing the '&notes=Banned by Fail2Ban' URL parameter. The spaces were causing curl to fail during my testing. There is probably a more elegant way to include the spaces.

`actionunban = curl -s -X GET -H "Authorization: Bearer <cfkey>" -H "Content-Type: application/json" \
        "https://api.cloudflare.com/client/v4/user/firewall/access_rules/rules?page=1&per_page=5&mode=block&configuration.target=ip&configuration.value=<ip>&match=all&order=configuration.value&direction=desc" | \
    python3 -c "import sys, json; print(json.load(sys.stdin)['result'][0]['id']);" | \
        xargs -I@@ curl -s -X DELETE -H "Authorization: Bearer <cfkey>" -H "Content-Type: application/json" https://api.cloudflare.com/client/v4/user/firewall/access_rules/rules/@@`

Regards.

**Comment by wpkc** [comment]
If this fail2ban action is the only thing sending IP ban commands to CloudFlare, then the "Banned by Fail2Ban" search parameter in actionunban isn't really necessary.  It was just there to make sure actionunban does interfere with other security software.

The maintainer of fail2ban has said several times that he would prefer not having scripting, like curl and other command line executables, in actions.  So it is probably better if I rewrite all of this in "native code" for fail2ban, which is pure python.
